### ISSUE TITLE
[5pts] Paper Prototyping

### ISSUE THREAD

**Issue by Foxworth22** [Bestagons/quack#26]
**Fill in the blanks**:
As a developer, I would like to paper prototype the app UI, so that I can be most efficient when coding the app frontend.

- [x] Print out and Test
- [x] Make revisions

**Comment by MimiOlayeye** [comment]
- [ ] Print out and Test
- [ ] Make revisions

**Comment by MimiOlayeye** [comment]
https://www.canva.com/design/DAErIcbY5yo/share/preview?token=vrdBJpKXBbiyoBSLNRp4Hg&role=EDITOR&utm_content=DAErIcbY5yo&utm_campaign=designshare&utm_medium=link&utm_source=sharebutton

**Comment by brendacano** [comment]
(Star List Page) : haha I love how the red marks cross out the star list

(Profile Page): I'm confused on the "Funds" part and "Favorites" part. Cause isn't favorites part of the bottom heart icon and isn't "Funds" basically "Balances" on the side bar.  Some clarification will help (and Im guessing you will also create a prototype for those pages as well which would make it clearer)

Otherwise I think it looks good

**Comment by MimiOlayeye** [comment]
@brendacano Yeah I forgot to remove that! thanks for pointing that out!!

**Comment by RafaelPiloto10** [comment]
Thank you for being so thorough on this @MimiOlayeye, it looks great!
